### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chinnikrishna55** [caffe2/models#6]
What does this mean?

RuntimeError: [enforce fail at cross_entropy_op.cc:30] (label.ndim() == 1) || (label.ndim() == 2 && label.dim32(1) == 1).  Error from operator: 
input: "softmax" input: "label" output: "xent" name: "" type: "LabelCrossEntropy"

**Comment by benhsu75** [comment]
I am also having this issue

**Comment by abntu** [comment]
I got a similar error when I used a vector as label instead of using a single integer as label for each class, i.e. using label=[0, 0, 1, 0] instead of using label= 2. 
The code expects one dimension for label (label.ndim() == 1), however the data has 2 dimension: (label.ndim() == 2). So, if each sample is not belong to multiple classes you can change your label to integer using a max function.

**Comment by orionr** [comment]
@chinnikrishna55, if you're stilling having issues with this please move the conversation over to caffe2/caffe2. Thank you.
